apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: sentiment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: sentiment-consumer:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "tweets"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      restartPolicy: Always
