apiVersion: v1
kind: Secret
metadata:
  name: twitter-secrets
  namespace: sentiment
type: Opaque
stringData:
  TWITTER_API_KEY: "REPLACE_ME"
  TWITTER_API_SECRET: "REPLACE_ME"
  TWITTER_BEARER_TOKEN: "REPLACE_ME"
